//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetableServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeTableEntities : DbContext
    {
        public TimeTableEntities()
            : base("name=TimeTableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<classroom> classrooms { get; set; }
        public virtual DbSet<croomtype> croomtypes { get; set; }
        public virtual DbSet<day> days { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<semester> semesters { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<teaching> teachings { get; set; }
        public virtual DbSet<title> titles { get; set; }
    }
}
