//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetableServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        public string idlessons { get; set; }
        public string idteachers { get; set; }
        public string idsubjects { get; set; }
        public string idclassrooms { get; set; }
        public string iddays { get; set; }
        public string idgroups { get; set; }
    
        public virtual classroom classroom { get; set; }
        public virtual day day { get; set; }
        public virtual group group { get; set; }
        public virtual subject subject { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
