//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimetableServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class teaching
    {
        public string idteachers { get; set; }
        public string idsubjects { get; set; }
        public string idmain { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
